/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {ParamValue, RouteRecordInfo,} from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/docs/': RouteRecordInfo<'/docs/', '/docs', Record<never, never>, Record<never, never>>,
    '/docs/[packageName]/[packageVersion]/': RouteRecordInfo<'/docs/[packageName]/[packageVersion]/', '/docs/:packageName/:packageVersion', {
      packageName: ParamValue<true>,
      packageVersion: ParamValue<true>
    }, { packageName: ParamValue<false>, packageVersion: ParamValue<false> }>,
  }
}
