[package]
name = "felico-lexer"
version = "0.1.0"
edition = "2024"

[dependencies]
felico-base = { path = "../base" }
felico-source = { path = "../source" }

[dev-dependencies]
expect-test = { workspace = true }